export enum ExpoStatus {
  PREVIO_CARGUE,
  TRANSITO_PUERTO,
  EN_PUERTO,
  TRANSITO_INTERNACIONAL,
  EN_DESTINO,
  FINALIZADO,
}

export enum ProgressStatus {
  SIN_INICIAR,
  EN_CURSO,
  EN_ESPERA,
  RETRASADO,
  COMPLETADO,
}

export const initialExpoSettingList = [
  {
    // id: "1",
    name: "Solicitud de reserva",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "2",
    name: "Confirmación de reserva",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "3",
    name: "Coordinación de transporte terrestre",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "4",
    name: "Notificación al agente de aduanas",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "5",
    name: "Cargue en planta",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "6",
    name: "Ingreso a puerto",
    status: ExpoStatus.TRANSITO_PUERTO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "7",
    name: "Aprobación documento de transporte",
    status: ExpoStatus.EN_PUERTO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "8",
    name: "Confirmación zarpe",
    status: ExpoStatus.EN_PUERTO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "9",
    name: "Notificar al cliente",
    status: ExpoStatus.TRANSITO_INTERNACIONAL,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "10",
    name: "Enviar documentos originales al cliente",
    status: ExpoStatus.TRANSITO_INTERNACIONAL,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "11",
    name: "Confirmación arribo a destino",
    status: ExpoStatus.TRANSITO_INTERNACIONAL,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "12",
    name: "Confirmación entrega final al cliente",
    status: ExpoStatus.FINALIZADO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "13",
    name: "DEX",
    status: ExpoStatus.FINALIZADO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "14",
    name: "Legalización divisas",
    status: ExpoStatus.EN_DESTINO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "15",
    name: "Liquidación",
    status: ExpoStatus.EN_DESTINO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "16",
    name: "Aprobación documentos y archivo",
    status: ExpoStatus.EN_DESTINO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
];
