
export enum ExpoStatus {
  PrevioCargue = "Previo Cargue",
  TransitoPuerto = "Transito Puerto",
  EnPuerto = "En Puerto",
  TransitoInternacional = "Transito Internacional",
  EnDestino = "En Destino",
  Finalizado = "Finalizado",
}

export enum ProgressStatus {
  "Sin iniciar" = "Sin iniciar",
  "En curso" = "En curso",
  "En espera" = "En espera",
  "Retrasado" = "Retrasado",
  "Completado" = "Completado",
}

export const initialExpoSettingList = [
  {
    // id: "1",
    name: "Solicitud de reserva",
    status: ExpoStatus.PrevioCargue,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "2",
    name: "Confirmación de reserva",
    status: ExpoStatus.PrevioCargue,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "3",
    name: "Coordinación de transporte terrestre",
    status: ExpoStatus.PrevioCargue,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "4",
    name: "Notificación al agente de aduanas",
    status: ExpoStatus.PrevioCargue,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "5",
    name: "Cargue en planta",
    status: ExpoStatus.PrevioCargue,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "6",
    name: "Ingreso a puerto",
    status: ExpoStatus.TransitoPuerto,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "7",
    name: "Aprobación documento de transporte",
    status: ExpoStatus.EnPuerto,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "8",
    name: "Confirmación zarpe",
    status: ExpoStatus.EnPuerto,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "9",
    name: "Notificar al cliente",
    status: ExpoStatus.TransitoInternacional,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "10",
    name: "Enviar documentos originales al cliente",
    status: ExpoStatus.TransitoInternacional,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "11",
    name: "Confirmación arribo a destino",
    status: ExpoStatus.TransitoInternacional,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "12",
    name: "Confirmación entrega final al cliente",
    status: ExpoStatus.Finalizado,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "13",
    name: "DEX",
    status: ExpoStatus.Finalizado,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "14",
    name: "Legalización divisas",
    status: ExpoStatus.EnDestino,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "15",
    name: "Liquidación",
    status: ExpoStatus.EnDestino,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    // id: "16",
    name: "Aprobación documentos y archivo",
    status: ExpoStatus.EnDestino,
    progress: ProgressStatus["Sin iniciar"],
    responsible: "",
    optional: false,
    enabled: true,
  },
];

