import { ExpoStatus, ProgressStatus } from "@prisma/client";

export const initialExpoSettingList = [
  {
    name: "Solicitud de reserva",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Confirmación de reserva",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Coordinación de transporte terrestre",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Notificación al agente de aduanas",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Cargue en planta",
    status: ExpoStatus.PREVIO_CARGUE,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Ingreso a puerto",
    status: ExpoStatus.TRANSITO_PUERTO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Aprobación documento de transporte",
    status: ExpoStatus.EN_PUERTO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Confirmación zarpe",
    status: ExpoStatus.EN_PUERTO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Notificar al cliente",
    status: ExpoStatus.TRANSITO_INTERNACIONAL,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Enviar documentos originales al cliente",
    status: ExpoStatus.TRANSITO_INTERNACIONAL,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Confirmación arribo a destino",
    status: ExpoStatus.TRANSITO_INTERNACIONAL,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Confirmación entrega final al cliente",
    status: ExpoStatus.FINALIZADO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "DEX",
    status: ExpoStatus.FINALIZADO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Legalización divisas",
    status: ExpoStatus.EN_DESTINO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Liquidación",
    status: ExpoStatus.EN_DESTINO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
  {
    name: "Aprobación documentos y archivo",
    status: ExpoStatus.EN_DESTINO,
    progress: ProgressStatus.SIN_INICIAR,
    responsible: "",
    optional: false,
    enabled: true,
  },
];
